set(
  LIBM_SOURCE_FILES_DOUBLE
  e_acos.c
  e_acosh.c
  e_asin.c
  e_atan2.c
  e_atanh.c
  e_cosh.c
  e_exp.c
  e_fmod.c
  e_hypot.c
  e_j0.c
  e_j1.c
  e_jn.c
  e_lgamma.c
  e_lgamma_r.c
  e_log.c
  e_log10.c
  e_log2.c
  e_pow.c
  e_rem_pio2.c
  e_remainder.c
  e_sinh.c
  e_sqrt.c
  k_cos.c
  k_exp.c
  k_log.h
  k_rem_pio2.c
  k_sin.c
  k_tan.c
  s_asinh.c
  s_atan.c
  s_ceil.c
  s_cos.c
  s_copysign.c
  s_erf.c
  s_exp2.c
  s_expm1.c
  s_fabs.c
  s_fdim.c
  s_floor.c
  s_fmax.c
  s_fmin.c
  s_frexp.c
  s_ilogb.c
  s_isfinite.c
  s_isnan.c
  s_isnormal.c
  s_llrint.c
  s_llround.c
  s_log1p.c
  s_logb.c
  s_lrint.c
  s_lround.c
  s_modf.c
  s_nan.c
  s_nearbyint.c
  s_nextafter.c
  #    s_nexttoward.c
  s_remquo.c
  s_rint.c
  s_round.c
  s_scalbln.c
  s_scalbn.c
  s_signbit.c
  s_signgam.c
  s_sin.c
  s_sincos.c
  s_tan.c
  s_tanh.c
  s_trunc.c
  w_cabs.c
)

set(
  LIBM_SOURCE_FILES_FLOAT
  e_acosf.c
  e_acoshf.c
  e_asinf.c
  e_atan2f.c
  e_atanhf.c
  e_coshf.c
  e_expf.c
  e_fmodf.c
  e_hypotf.c
  e_j0f.c
  e_j1f.c
  e_jnf.c
  e_lgammaf.c
  e_logf.c
  e_log10f.c
  e_log2f.c
  e_powf.c
  e_rem_pio2f.c
  e_remainderf.c
  e_sinhf.c
  e_sqrtf.c
  k_cosf.c
  k_expf.c
  k_logf.h
  k_sinf.c
  k_tanf.c
  s_asinhf.c
  s_atanf.c
  s_ceilf.c
  s_cosf.c
  s_copysignf.c
  s_erff.c
  s_exp2f.c
  s_expm1f.c
  s_fabsf.c
  s_floorf.c
  s_fmaxf.c
  s_fminf.c
  s_frexpf.c
  s_ilogbf.c
  s_llrintf.c
  s_llroundf.c
  s_log1pf.c
  s_logbf.c
  s_lrintf.c
  s_lroundf.c
  s_modff.c
  s_nextafterf.c
  s_remquof.c
  s_rintf.c
  s_roundf.c
  s_scalbnf.c
  s_sinf.c
  s_sincosf.c
  s_tanf.c
  s_tanhf.c
  s_truncf.c
  w_cabsf.c
)

set(
  libm_flags
  -Wno-pedantic
  -Wno-reserved-id-macro
  -Wno-sign-conversion
  -Wno-sign-compare
  -Wno-cast-qual
  -Wno-float-equal
  -Wno-conditional-uninitialized
  -Wno-disabled-macro-expansion
  -Wno-implicit-fallthrough
  -Wno-implicit-const-int-float-conversion
  -Wno-float-conversion
  -Wno-bad-function-cast
  -Wno-double-promotion
  -Wno-implicit-float-conversion
  -D__BSD_VISIBLE
)

list(JOIN libm_flags " " LIBM_FLAGS)

set(LIBM_SOURCE_FILES)
list(APPEND LIBM_SOURCE_FILES ${LIBM_SOURCE_FILES_FLOAT})
list(APPEND LIBM_SOURCE_FILES ${LIBM_SOURCE_FILES_DOUBLE})
list(TRANSFORM LIBM_SOURCE_FILES PREPEND "${CMAKE_CURRENT_LIST_DIR}/src/")

set_source_files_properties(${LIBM_SOURCE_FILES} PROPERTIES COMPILE_FLAGS "${LIBM_FLAGS}")
